spring:
    application:
        name: jwtlibrary

# JWT Configuration
jwt:
    create-account:
        secretKey: your-256-bit-secret-your-256-bit-secret-your-256-bit-secret1
        expiration: 1200 # 20 min
        algorithm: HS256
        claims: ['email', 'name']
    reset-passwd:
        secretKey: your-256-bit-secret-your-256-bit-secret-your-256-bit-secret2
        expiration: 600 # 10 min
        algorithm: RS256
    login:
        secretKey: your-256-bit-secret-your-256-bit-secret-your-256-bit-secret3
        expiration: 3600000 # 1 hour
        algorithm: RS512
        claims: ['role']